config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'users#index'

  resources :users
  # resources :session

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  put 'add_patient', to: 'users#add_patient'
  get 'patient_registration', to: 'users#patient_registration'
  get 'patients', to: 'users#patients'

  namespace 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      post 'signup', to: 'users#create'
      post 'login', to: 'sessions#create'
      post 'logout', to: 'sessions#destroy'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :sessions

  enum position: [:doctor, :patient]
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  skip_before_action :authenticate!, only: [:create]

  # Show individual profile info
  def show
    result = Individuals::Show.call(individual_id: params[:id], current_profile: current_profile)

    render resource_render_params(
      result,
      serializer: ::V1::Individuals::IndividualSerializer
    )
  end

  def create
    result = Users::Create.call(profile_params: profile_params)
    render resource_render_params(result, serializer: ::V1::UserSerializer)
  end

  def upload_avatar
    result = Individuals::UploadAvatar.call(
      caller_profile: current_profile,
      avatar: params[:avatar]
    )

    render resource_render_params(
      result,
      serializer: ::V1::Individuals::IndividualSerializer
    )
  end

  def destroy_avatar
    result = Individuals::DestroyAvatar.call(
      caller_profile: current_profile,
      caller_company: current_company
    )

    render resource_render_params(
      result,
      serializer: ::V1::Individuals::IndividualSerializer
    )
  end

  private

  def profile_params
    params.permit(:email, :password, :password_confirmation, :first_name, :last_name, :patronymic, :birthday)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:add_patient, :patients, :index, :patient_registration]

  def index
    @patients = User.where(doctor_id: current_user.id)
  end

  def create
    result = Users::Create.call(params: user_params)

    if result.success?
      redirect_to login_path
    else
      flash.now[:message] = t(result.message)
      render :new
    end
  end

  def patient_registration

  end

  def patients
    @patients = User.where(position: :patient)
  end

  def add_patient
    result = Users::AddPatient.call(
      patient_id: params[:patient_id],
      current_user: current_user
    )

    if result.success?
      redirect_to patients_path
    else
      flash.now[:message] = t(result.message)
      redirect_to patients_path
    end
  end

  def new
    @user = User.new
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation, :first_name, :last_name, :patronymic, :birthday)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_menu.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
.w3-sidebar {width: 120px;background: #222;}
#main {margin-left: 120px}
@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="w3-black">

<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  <%# <img src="/w3images/avatar_smoke.jpg" style="width:100%"> %>
  <a href="#" class="w3-bar-item w3-button w3-padding-large w3-black">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>Главная</p>
  </a>
  <a href="#about" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>Регистрация пациента</p>
  </a>
  <a href="#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-eye w3-xxlarge"></i>
    <p>Назначить пациента</p>
  </a>
  <%# <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-envelope w3-xxlarge"></i>
    <p>CONTACT</p>
  </a> %>
</nav>

app/views/users/_modal.html.erb
<div id="myModalForm" class="my-modal">
  <div class="modal-content">
    <%= form_tag("/add_patient", method: "put") do %>
      <div class="modal-header">
        <span class="close">&times;</span>
        <h2>Добавить пациента</h2>
      </div>
      <div class="my-modal-body">
        <div class="custom-select" style="width:200px;">
          <%= select_tag "patient_id", options_from_collection_for_select(User.all, "id", "first_name", "1")%>
        </div>
      </div>
      <div class="modal-footer">
        <h3>Modal Footer</h3>
        <%= submit_tag("Добавить") %>
      </div>
    <% end %>
  </div>
</div>

<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.my-modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    position: relative;
    background-color: #fefefe;
    margin: auto;
    padding: 0;
    border: 1px solid #888;
    width: 80%;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
    -webkit-animation-name: animatetop;
    -webkit-animation-duration: 0.4s;
    animation-name: animatetop;
    animation-duration: 0.4s
}

/* Add Animation */
@-webkit-keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
}

@keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
}

/* The Close Button */
.close {
    color: white;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}

.modal-header {
    padding: 2px 16px;
    background-color: #5cb85c;
    color: white;
}

.my-modal-body {padding: 2px 16px;}

.modal-footer {
    padding: 2px 16px;
    background-color: #5cb85c;
    color: white;
}
</style>

<script>
// Get the modal
var modal = document.getElementById('myModalForm');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<style>
/*the container must be positioned relative:*/
.custom-select {
  position: relative;
  font-family: Arial;
}
.custom-select select {
  display: none; /*hide original SELECT element:*/
}
.select-selected {
  background-color: DodgerBlue;
}
/*style the arrow inside the select element:*/
.select-selected:after {
  position: absolute;
  content: "";
  top: 14px;
  right: 10px;
  width: 0;
  height: 0;
  border: 6px solid transparent;
  border-color: #fff transparent transparent transparent;
}
/*point the arrow upwards when the select box is open (active):*/
.select-selected.select-arrow-active:after {
  border-color: transparent transparent #fff transparent;
  top: 7px;
}
/*style the items (options), including the selected item:*/
.select-items div,.select-selected {
  color: #ffffff;
  padding: 8px 16px;
  border: 1px solid transparent;
  border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
  cursor: pointer;
  user-select: none;
}
/*style items (options):*/
.select-items {
  position: absolute;
  background-color: DodgerBlue;
  top: 100%;
  left: 0;
  right: 0;
  z-index: 99;
}
/*hide the items when the select box is closed:*/
.select-hide {
  display: none;
}
.select-items div:hover {
  background-color: rgba(0, 0, 0, 0.1);
}
</style>

<script>
var x, i, j, selElmnt, a, b, c;
/*look for any elements with the class "custom-select":*/
x = document.getElementsByClassName("custom-select");
for (i = 0; i < x.length; i++) {
  selElmnt = x[i].getElementsByTagName("select")[0];
  /*for each element, create a new DIV that will act as the selected item:*/
  a = document.createElement("DIV");
  a.setAttribute("class", "select-selected");
  a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
  x[i].appendChild(a);
  /*for each element, create a new DIV that will contain the option list:*/
  b = document.createElement("DIV");
  b.setAttribute("class", "select-items select-hide");
  for (j = 1; j < selElmnt.length; j++) {
    /*for each option in the original select element,
    create a new DIV that will act as an option item:*/
    c = document.createElement("DIV");
    c.innerHTML = selElmnt.options[j].innerHTML;
    c.addEventListener("click", function(e) {
        /*when an item is clicked, update the original select box,
        and the selected item:*/
        var i, s, h;
        s = this.parentNode.parentNode.getElementsByTagName("select")[0];
        h = this.parentNode.previousSibling;
        for (i = 0; i < s.length; i++) {
          if (s.options[i].innerHTML == this.innerHTML) {
            s.selectedIndex = i;
            h.innerHTML = this.innerHTML;
            break;
          }
        }
        h.click();
    });
    b.appendChild(c);
  }
  x[i].appendChild(b);
  a.addEventListener("click", function(e) {
      /*when the select box is clicked, close any other select boxes,
      and open/close the current select box:*/
      e.stopPropagation();
      closeAllSelect(this);
      this.nextSibling.classList.toggle("select-hide");
      this.classList.toggle("select-arrow-active");
    });
}
function closeAllSelect(elmnt) {
  /*a function that will close all select boxes in the document,
  except the current select box:*/
  var x, y, i, arrNo = [];
  x = document.getElementsByClassName("select-items");
  y = document.getElementsByClassName("select-selected");
  for (i = 0; i < y.length; i++) {
    if (elmnt == y[i]) {
      arrNo.push(i)
    } else {
      y[i].classList.remove("select-arrow-active");
    }
  }
  for (i = 0; i < x.length; i++) {
    if (arrNo.indexOf(i)) {
      x[i].classList.add("select-hide");
    }
  }
}
/*if the user clicks anywhere outside the select box,
then close all select boxes:*/
document.addEventListener("click", closeAllSelect);
</script>

app/views/users/index.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
.w3-sidebar {width: 120px;background: #222;}
#main {margin-left: 120px}
@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="w3-black">

<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  <a href="/" class="w3-bar-item w3-button w3-padding-large w3-black">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>Главная</p>
  </a>
  <a href="/patients" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>Пациенты</p>
  </a>
  <a href="/patient_registration" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-address-book-o w3-xxlarge"></i>
    <p>Регистрация пациента</p>
  </a>

  <a href="logout" class="w3-bar-item w3-button w3-padding-large w3-hover-black" data-method="delete">
    <i class="fa fa-close w3-xxlarge"></i>
    <p>CONTACT</p>
  </a>
</nav>

<div class="w3-padding-large" id="main">
  <table class="container">
    <thead>
      <tr>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>Дата рождения</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.patronymic %></td>
        <td><%= patient.birthday.strftime("%d.%m.%Y") %></td>
      </tr>
      <% end%>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="form">
	<ul class="tab-group">
		<li class="tab active"><a href="signup">Sign Up</a></li>
		<li class="tab"><a href="login">Log In</a></li>
	</ul>

	<%= form_tag("/signup", method: "post") do %>
		<h1>Добро пожаловать!</h1>
		<div id="login">
			<div class="field-wrap">
				<label>
					Email<span class="req">*</span>
				</label>
					<%= email_field :email, params[:email], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Пароль<span class="req">*</span>
				</label>
				<%= password_field_tag :password, nil, autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Подтверждения пароля<span class="req">*</span>
				</label>
				<%= password_field_tag :password_confirmation, nil, autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Имя<span class="req">*</span>
				</label>
					<%= text_field_tag :first_name, params[:first_name], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Фамилия<span class="req">*</span>
				</label>
					<%= text_field_tag :last_name, params[:last_name], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Отчество<span class="req">*</span>
				</label>
					<%= text_field_tag :patronymic, params[:patronymic], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Дата рождения<span class="req">*</span>
				</label>
					<%= text_field_tag :birthday, params[:birthday], autocomplete: "off" %>
			</div>

			<%= submit_tag "Войти", class: "button button-block" %>
		</div>
	<% end %>
</div>

<script>
	$('.form').find('input, textarea').on('keyup blur focus', function (e) {

		var $this = $(this),
				label = $this.prev('label');

			if (e.type === 'keyup') {
				if ($this.val() === '') {
						label.removeClass('active highlight');
					} else {
						label.addClass('active highlight');
					}
			} else if (e.type === 'blur') {
				if( $this.val() === '' ) {
					label.removeClass('active highlight');
				} else {
					label.removeClass('highlight');
				}
			} else if (e.type === 'focus') {

				if( $this.val() === '' ) {
					label.removeClass('highlight');
				}
				else if( $this.val() !== '' ) {
					label.addClass('highlight');
				}
			}

	});
</script>

app/views/users/patient_registration.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
  .w3-row-padding img {margin-bottom: 12px}
  .w3-sidebar {width: 120px;background: #222;}
  #main {margin-left: 120px}
  @media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="w3-black">
  <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
    <a href="/" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
      <i class="fa fa-home w3-xxlarge"></i>
      <p>Главная</p>
    </a>
    <a href="/patients" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
      <i class="fa fa-user w3-xxlarge"></i>
      <p>Пациенты</p>
    </a>
    <a href="/patient_registration" class="w3-bar-item w3-button w3-padding-large w3-black">
      <i class="fa fa-address-book-o w3-xxlarge"></i>
      <p>Регистрация пациента</p>
    </a>
    <a href="logout" class="w3-bar-item w3-button w3-padding-large w3-hover-black" data-method="delete">
      <i class="fa fa-close w3-xxlarge"></i>
      <p>CONTACT</p>
    </a>
  </nav>
<div class="w3-padding-large" id="main">
	<%= form_tag("/signup", method: "post") do %>
		<h1>Регистрация пациента</h1>
		<div id="login">
			<div class="field-wrap">
				<label>
					Email<span class="req">*</span>
				</label>
					<%= email_field :email, params[:email], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Пароль<span class="req">*</span>
				</label>
				<%= password_field_tag :password, nil, autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Подтверждения пароля<span class="req">*</span>
				</label>
				<%= password_field_tag :password_confirmation, nil, autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Имя<span class="req">*</span>
				</label>
					<%= text_field_tag :first_name, params[:first_name], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Фамилия<span class="req">*</span>
				</label>
					<%= text_field_tag :last_name, params[:last_name], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Отчество<span class="req">*</span>
				</label>
					<%= text_field_tag :patronymic, params[:patronymic], autocomplete: "off" %>
			</div>

			<div class="field-wrap">
				<label>
					Дата рождения<span class="req">*</span>
				</label>
					<%= text_field_tag :birthday, params[:birthday], autocomplete: "off" %>
			</div>

			<%= submit_tag "Регистрация", class: "button button-block" %>
		</div>
	<% end %>
</div>
</body>

app/views/users/patients.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
.w3-sidebar {width: 120px;background: #222;}
#main {margin-left: 120px}
@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="w3-black">

<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  <a href="/" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>Главная</p>
  </a>
  <a href="/patients" class="w3-bar-item w3-button w3-padding-large w3-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>Пациенты</p>
  </a>
  <a href="/patient_registration" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-address-book-o w3-xxlarge"></i>
    <p>Регистрация пациента</p>
  </a>
  <a href="logout" class="w3-bar-item w3-button w3-padding-large w3-hover-black" data-method="delete">
    <i class="fa fa-close w3-xxlarge"></i>
    <p>CONTACT</p>
  </a>
</nav>
</body>

<div class="w3-padding-large" id="main">
  <table class="container">
    <thead>
      <tr>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>Дата рождения</th>
        <th>Действие</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.patronymic %></td>
        <td><%= patient.birthday %></td>
        <td><%= link_to "Добавить", add_patient_path(patient_id: patient.id), method: :put %></td>
      </tr>
      <% end%>
    </tbody>
  </table>
</div>